# See http://about.travis-ci.org/docs/user/build-configuration/

language: scala
scala:
  - "2.10.0"

branches:
  only:
    - develop

notifications:
  email:
    recipients:
      - dev@crashnote.com

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7